/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_nonocast_App */

#ifndef _Included_cn_nonocast_App
#define _Included_cn_nonocast_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_nonocast_App
 * Method:    calc
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_nonocast_App_calc
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
